#!/bin/bash -f
clear

echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo "::::::::::::                      ::::::::::::::"
echo "::::::::::::      PREBEPLAYER     ::::::::::::::"
echo "::::::::::::                      ::::::::::::::"
echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo ""
echo ""
echo ""
echo "----------------------------------------[ Ayuda ]"
echo ""
echo "1) Para moverte sobre los menus, ingresa los"
echo "  numeros de opcion."
echo ""
echo "2) En el menu Reproducir, escribe el nombre de la"
echo "  cancion. Por default, la ruta de inicio esta"
echo "  asignada en el archivo de configuracion"
echo "  'config.txt', modifica la Ruta de Exploracion"
echo "  para indicar donde quieres iniciar el programa."
echo ""
echo "3) En el menu Libreria, tienes explora las carpetas"
echo "  para buscar mas musica que reproducir."
echo ""
echo "4) En el menu Controles, reproduce, pausa, para"
echo "  ajusta el volumen y agrega tus canciones a"
echo "  favoritos."
echo ""
echo "5) Gracias por utilizar PREBEPLAYER, mi numero de"
echo "  cuenta bancaria es: 19284 23923 12912, aceptamos"
echo "  depositos mayores a 100 pesos."
echo ""
echo "-------------------------------------------------"
echo ""
echo "Presiona [enter] para continuar."